### ISSUE TITLE
Changelog file

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-base#26]
Hello,
from now on we need to maintain a changelog file. It's interesting for several reasons but the main reason I want it is so I can refer to that when releasing a new version instead of having to go through the PRs. The idea os to have something like:

v1.14.0
----------

* #13 [new_method] get_ntp_peers
* #22 [bugfix] blah blah blah
..

I think we should have the following tags:

* new_method, bugfix, enhancement, documentation

Thoughts?

@mirceaulinic @ktbyers @fooelisa

**Comment by mirceaulinic** [comment]
If we add the milestone isn't helpful?

However, it's not hard of maintain a changelog file (but where is it?). I'm really thinking that maybe would be interesting and easier to use a ticketing system for that instead of editing files. What do you think?

Somehow, we can relate this with my comments on https://github.com/napalm-automation/napalm/pull/244.

**Comment by dbarrosop** [comment]
Damn it! I replied on the wrong thread!!!

The milestone helped but I still have to copy paste a few times and fix the formatting. An alternative would be to have a changelog message on the PR so at least I have something to copy paste that I don't have to reformat (the title of the PR is not that friendly).
